### ISSUE TITLE
New update doesn't show up inside the app

### ISSUE THREAD

**Issue by I-am-Gaming** [shmykelsa/AAAD#365]
Just now received update about 2.6.1 via notification. After openjng the app via notification, update doesn't show up

![SmartSelect_20251217_225905_AAAD.jpg](https://github.com/user-attachments/assets/d263bb94-2c37-4eda-8125-97ded103411d)

**Comment by KinG-InFeT** [comment]
+1

**Comment by shmykelsa** [comment]
Have you tried closing and opening back AAAD?

**Comment by KinG-InFeT** [comment]
> Have you tried closing and opening back AAAD?

Yes, but same issue

**Comment by I-am-Gaming** [comment]
> Have you tried closing and opening back AAAD?

Yes , I even tried clearing cache and force stop. It seems like its fixed on 2.6.1

**Comment by KinG-InFeT** [comment]
Now click on notification from 2.6.2 update and install 2.6.1, after installer 2.6.1, insode the app out the 2.6.2 update and installed it. The bug present into 2.6 version or fixed in 2.6.1

**Comment by I-am-Gaming** [comment]
![Image](https://github.com/user-attachments/assets/6712a350-3f4c-4bae-bfa6-bdd9cce64bc9)

It still happening in 2.6.2

**Comment by KinG-InFeT** [comment]
Bug regression into 2.6.2, not show 2.6.3 update into.the app after click on notification update
